import { localized as l, type ApiEndpoint } from './apiCatalogTypes'

export const iCloudEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/icloud/accounts', group: 'icloud', auth: 'authenticated',
    title: l('列出 iCloud 账户', 'List iCloud accounts'),
    description: l('返回当前用户连接的 iCloud 账户，不解密或返回凭据。', 'Return the current user’s connected iCloud accounts without decrypting or returning credentials.'),
    request: 'No parameters', response: '200 · { accounts }',
  },
  {
    method: 'POST', path: '/api/icloud/accounts', group: 'icloud', auth: 'authenticated',
    title: l('连接 iCloud 账户', 'Connect an iCloud account'),
    description: l('通过应用专用密码连接主邮箱，或通过 Cookie 管理隐藏邮箱；两种方式可单独或同时配置。', 'Connect primary mail with an app-specific password, manage aliases with cookies, or configure both.'),
    request: 'JSON · name, cookies?, host=icloud.com|icloud.com.cn, icloudEmail?, appPassword?', response: '201 · { account }',
    exampleBody: { name: 'My iCloud', cookies: { X_APPLE_WEB_KB: 'cookie-value' }, host: 'icloud.com' },
    notes: [l('Cookie 属于高敏感凭据，只应提交给自己的 OmniMail 实例。', 'Cookies are highly sensitive credentials and should only be sent to your own OmniMail instance.')],
  },
  {
    method: 'PATCH', path: '/api/icloud/accounts/:id', group: 'icloud', auth: 'authenticated',
    title: l('修改 iCloud 账户备注', 'Rename an iCloud account'),
    description: l('修改当前用户连接的 iCloud 账户备注名称。', 'Change the display name of an iCloud account connected by the current user.'),
    request: 'Path · id; JSON · name', response: '200 · { ok: true, name }',
    exampleBody: { name: 'Personal iCloud' },
  },
  {
    method: 'DELETE', path: '/api/icloud/accounts/:id', group: 'icloud', auth: 'authenticated',
    title: l('删除 iCloud 账户', 'Delete an iCloud account'),
    description: l('删除当前用户的加密 Cookie、应用专用密码和账户记录。', 'Delete the current user’s encrypted cookies, app password, and account record.'),
    request: 'Path · id', response: '200 · { ok: true }',
  },
  {
    method: 'PUT', path: '/api/icloud/accounts/:id/cookies', group: 'icloud', auth: 'authenticated',
    title: l('更新 iCloud Cookie', 'Update iCloud cookies'),
    description: l('覆盖并重新验证账户 Cookie，同时刷新别名统计。', 'Replace and revalidate account cookies, then refresh alias statistics.'),
    request: 'Path · id; JSON · cookies', response: '200 · { account }',
    exampleBody: { cookies: { X_APPLE_WEB_KB: 'new-cookie-value' } },
  },
  {
    method: 'PUT', path: '/api/icloud/accounts/:id/app-password', group: 'icloud', auth: 'authenticated',
    title: l('设置 iCloud 应用专用密码', 'Set an iCloud app-specific password'),
    description: l('验证 IMAP 登录后加密保存 iCloud 邮箱和应用专用密码。', 'Validate IMAP login, then encrypt the iCloud email and app-specific password.'),
    request: 'Path · id; JSON · icloudEmail, appPassword', response: '200 · { ok: true, icloudEmail }',
    exampleBody: { icloudEmail: 'owner@icloud.com', appPassword: 'xxxx-xxxx-xxxx-xxxx' },
  },
  {
    method: 'GET', path: '/api/icloud/aliases', group: 'icloud', auth: 'authenticated',
    title: l('同步隐藏邮箱地址', 'Sync Hide My Email aliases'),
    description: l('从 Apple 读取指定账户的全部隐藏邮箱地址并刷新 Cookie。', 'Read all Hide My Email aliases for an account from Apple and refresh cookies.'),
    request: 'Query · accountId', response: '200 · { aliases }',
    examplePath: '/api/icloud/aliases?accountId=icloud_account_id',
  },
  {
    method: 'POST', path: '/api/icloud/aliases/preview', group: 'icloud', auth: 'authenticated',
    title: l('预览隐藏邮箱地址', 'Preview a Hide My Email address'),
    description: l('让 Apple 生成一个尚未创建的候选隐藏邮箱地址。', 'Ask Apple for a suggested Hide My Email address without creating it.'),
    request: 'JSON · accountId', response: '200 · { email, previewId }',
    exampleBody: { accountId: 'icloud_account_id' },
  },
  {
    method: 'POST', path: '/api/icloud/aliases', group: 'icloud', auth: 'authenticated',
    title: l('创建隐藏邮箱地址', 'Create a Hide My Email alias'),
    description: l('在指定 iCloud 账户中创建带标签的隐藏地址。', 'Create a labeled Hide My Email alias in the selected iCloud account.'),
    request: 'JSON · accountId, label?, email?, previewId?', response: '201 · { alias }',
    exampleBody: { accountId: 'icloud_account_id', label: 'Shopping', email: 'suggested@icloud.com', previewId: '00000000-0000-4000-8000-000000000001' },
  },
  {
    method: 'PATCH', path: '/api/icloud/aliases/:anonymousId', group: 'icloud', auth: 'authenticated',
    title: l('停用或恢复隐藏地址', 'Deactivate or reactivate an alias'),
    description: l('对指定 Apple anonymousId 执行停用或恢复。', 'Deactivate or reactivate the selected Apple anonymousId.'),
    request: 'Path · anonymousId; JSON · accountId, action=deactivate|reactivate', response: '200 · { ok: true, action }',
    exampleBody: { accountId: 'icloud_account_id', action: 'deactivate' },
  },
  {
    method: 'DELETE', path: '/api/icloud/aliases/:anonymousId', group: 'icloud', auth: 'authenticated',
    title: l('永久删除隐藏地址', 'Permanently delete an alias'),
    description: l('从 Apple 永久删除指定隐藏地址并刷新账户统计。', 'Permanently delete the alias from Apple and refresh account statistics.'),
    request: 'Path · anonymousId; JSON · accountId', response: '200 · { ok: true }',
    exampleBody: { accountId: 'icloud_account_id' },
  },
  {
    method: 'GET', path: '/api/icloud/inbox', group: 'icloud', auth: 'authenticated',
    title: l('读取 iCloud 最近来信', 'List recent iCloud mail'),
    description: l('通过 IMAP 读取或搜索最近邮件摘要；Web 回退仅过滤当前摘要。', 'Read or search recent IMAP message summaries; Web fallback filters current summaries only.'),
    request: 'Query · accountId, alias?, q?, limit=1..50?, days=0..365?', response: '200 · { messages, method=imap|web }',
    examplePath: '/api/icloud/inbox?accountId=icloud_account_id&limit=20&days=7',
  },
  {
    method: 'GET', path: '/api/icloud/inbox/:uid', group: 'icloud', auth: 'authenticated',
    title: l('读取 iCloud 邮件正文', 'Read an iCloud message'),
    description: l('通过 IMAP UID 读取完整正文，并将未读邮件同步标记为 Seen。', 'Read full content by IMAP UID and synchronize unread mail to Seen.'),
    request: 'Path · uid; Query · accountId', response: '200 · { message: { …, isRead=true } }',
    examplePath: '/api/icloud/inbox/:uid?accountId=icloud_account_id',
  },
]

export const gmailEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/gmail/accounts', group: 'gmail', auth: 'authenticated',
    title: l('列出 Gmail 账号', 'List Gmail accounts'),
    description: l('返回当前用户的脱敏 Gmail 账号和同步状态，不返回凭据或密文。', 'Return the current user’s sanitized Gmail accounts and sync state without credentials or ciphertext.'),
    request: 'No parameters', response: '200 · { enabled, accounts }',
  },
  {
    method: 'POST', path: '/api/gmail/accounts', group: 'gmail', auth: 'authenticated',
    title: l('连接 Gmail 账号', 'Connect a Gmail account'),
    description: l('验证固定 Gmail IMAP 端点后，用独立密钥加密保存应用专用密码。', 'Validate the fixed Gmail IMAP endpoint, then encrypt the app password with a dedicated key.'),
    request: 'JSON · name, email, appPassword', response: '201 · { account }',
    exampleBody: { name: 'Personal Gmail', email: 'owner@gmail.com', appPassword: 'xxxx xxxx xxxx xxxx' },
    notes: [l('只接受 Google 生成的 16 位应用专用密码；不要提交 Google 账号主密码。', 'Only a Google-generated 16-character app password is accepted; never submit the Google Account password.')],
  },
  {
    method: 'PATCH', path: '/api/gmail/accounts/:id', group: 'gmail', auth: 'authenticated',
    title: l('重命名 Gmail 账号', 'Rename a Gmail account'),
    description: l('修改当前用户 Gmail 账号的显示名称。', 'Change the display name of a Gmail account owned by the current user.'),
    request: 'Path · id; JSON · name', response: '200 · { account }',
    exampleBody: { name: 'Work Gmail' },
  },
  {
    method: 'PUT', path: '/api/gmail/accounts/:id/app-password', group: 'gmail', auth: 'authenticated',
    title: l('更新 Gmail 应用密码', 'Update a Gmail app password'),
    description: l('先验证新密码，再替换密文；验证失败时保留原凭据。', 'Validate the new password before replacing ciphertext; preserve the existing credential if validation fails.'),
    request: 'Path · id; JSON · appPassword', response: '200 · { account }',
    exampleBody: { appPassword: 'xxxx xxxx xxxx xxxx' },
  },
  {
    method: 'DELETE', path: '/api/gmail/accounts/:id', group: 'gmail', auth: 'authenticated',
    title: l('断开 Gmail 账号', 'Disconnect a Gmail account'),
    description: l('级联删除本地凭据和元数据索引，不会撤销 Google 端应用密码。', 'Cascade-delete local credentials and metadata without revoking the Google-side app password.'),
    request: 'Path · id', response: '200 · { ok, remoteRevocationRequired=true }',
  },
  {
    method: 'POST', path: '/api/gmail/accounts/:id/verify', group: 'gmail', auth: 'authenticated',
    title: l('验证 Gmail 连接', 'Verify a Gmail connection'),
    description: l('使用已保存凭据重新执行只读 Gmail IMAP 登录与 EXAMINE。', 'Use the saved credential to run read-only Gmail IMAP login and EXAMINE again.'),
    request: 'Path · id', response: '200 · { ok, validatedAt }',
  },
  {
    method: 'POST', path: '/api/gmail/accounts/:id/sync', group: 'gmail', auth: 'authenticated',
    title: l('请求 Gmail 同步', 'Request Gmail synchronization'),
    description: l('在频率限制和账号租约保护下，把只读同步任务加入 Queue。', 'Queue a read-only sync under rate limiting and an account lease.'),
    request: 'Path · id; JSON · limit=10|20|50?', response: '202 · { queued: true, limit }',
    exampleBody: { limit: 20 },
  },
  {
    method: 'GET', path: '/api/gmail/messages', group: 'gmail', auth: 'authenticated',
    title: l('列出 Gmail 聚合邮件', 'List unified Gmail messages'),
    description: l('按账号或全部账号搜索 D1 元数据索引，并使用稳定游标分页。', 'Search the D1 metadata index for one or all accounts with stable cursor pagination.'),
    request: 'Query · accountId?, q?, limit=1..50?, cursor?', response: '200 · { messages, page }',
    examplePath: '/api/gmail/messages?limit=30',
  },
  {
    method: 'GET', path: '/api/gmail/accounts/:accountId/messages/:messageId', group: 'gmail', auth: 'authenticated',
    title: l('读取 Gmail 正文', 'Read a Gmail message'),
    description: l('验证账号归属后，通过 BODY.PEEK[] 读取正文，并以受控 STORE 命令同步标记已读。', 'Verify account ownership, fetch the body with BODY.PEEK[], and synchronize Seen with a controlled STORE command.'),
    request: 'Path · accountId, messageId', response: '200 · { message }',
  },
  {
    method: 'GET', path: '/api/gmail/accounts/:accountId/messages/:messageId/attachments/:partId', group: 'gmail', auth: 'authenticated',
    title: l('下载 Gmail 附件', 'Download a Gmail attachment'),
    description: l('验证账号与邮件归属后，按需读取并转发不超过 5 MiB 的附件。', 'Verify account and message ownership, then fetch and proxy an attachment up to 5 MiB.'),
    request: 'Path · accountId, messageId, partId', response: '200 · attachment bytes',
    outputFile: 'gmail-attachment.bin',
  },
]

export const linuxDoMailEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/linux-do-mail/account', group: 'linuxdoMail', auth: 'authenticated',
    title: l('读取 Linux DO Mail 连接', 'Read the Linux DO Mail connection'),
    description: l('返回功能状态和当前用户的脱敏账号信息，不返回密码或认证令牌。', 'Return feature status and sanitized account metadata without returning the password or authentication token.'),
    request: 'No parameters', response: '200 · { enabled, account }',
  },
  {
    method: 'POST', path: '/api/linux-do-mail/account', group: 'linuxdoMail', auth: 'authenticated',
    title: l('连接 Linux DO Mail', 'Connect Linux DO Mail'),
    description: l('使用完整邮箱用户名和密码或认证令牌验证 IMAP，再加密保存凭据。', 'Validate IMAP with the full mailbox username and a password or authentication token, then encrypt the credential.'),
    request: 'JSON · username, password', response: '201 · { account }',
    exampleBody: { username: 'member@linux.do', password: 'authentication-token' },
    notes: [l('官方建议使用可撤销的专用认证令牌，不要提交邮箱主密码。', 'Linux DO recommends a revocable dedicated authentication token instead of the mailbox master password.')],
  },
  {
    method: 'DELETE', path: '/api/linux-do-mail/account', group: 'linuxdoMail', auth: 'authenticated',
    title: l('断开 Linux DO Mail', 'Disconnect Linux DO Mail'),
    description: l('删除当前用户的账号记录和凭据密文，不修改服务器端邮箱。', 'Delete the current user’s account record and encrypted credential without changing the server-side mailbox.'),
    request: 'No parameters', response: '200 · { ok: true }',
  },
  {
    method: 'POST', path: '/api/linux-do-mail/account/verify', group: 'linuxdoMail', auth: 'authenticated',
    title: l('验证 Linux DO Mail 凭据', 'Verify Linux DO Mail credentials'),
    description: l('重新登录 IMAP 并执行只读 EXAMINE INBOX。', 'Sign in to IMAP again and run the read-only EXAMINE INBOX command.'),
    request: 'No parameters', response: '200 · { ok: true, validatedAt }',
  },
  {
    method: 'PUT', path: '/api/linux-do-mail/account/credential', group: 'linuxdoMail', auth: 'authenticated',
    title: l('更新 Linux DO Mail 凭据', 'Update the Linux DO Mail credential'),
    description: l('先验证新密码或认证令牌，再替换已保存的密文；验证失败时保留原凭据。', 'Validate the new password or authentication token before replacing the saved ciphertext; keep the existing credential when validation fails.'),
    request: 'JSON · password', response: '200 · { account }',
    exampleBody: { password: 'new-authentication-token' },
    notes: [l('响应不会包含新旧凭据。', 'The response never contains the old or new credential.')],
  },
  {
    method: 'POST', path: '/api/linux-do-mail/messages', group: 'linuxdoMail', auth: 'authenticated',
    title: l('发送 Linux DO Mail 邮件', 'Send a Linux DO Mail message'),
    description: l('使用已连接账号通过 SMTP 465 异步发送邮件，并复用 OmniMail 的幂等、限速、队列和失败保护。', 'Send asynchronously through SMTP 465 with the connected account while reusing OmniMail idempotency, rate limits, queueing, and failure protection.'),
    request: 'JSON · to, subject, text, idempotencyKey', response: '200/202 · { message }',
    exampleBody: { to: 'recipient@example.net', subject: 'Hello', text: 'Message body', idempotencyKey: 'request_12345678' },
    notes: [
      l('From 固定为当前已验证的 Linux DO Mail 地址，不能由请求覆盖。', 'From is fixed to the currently verified Linux DO Mail address and cannot be overridden by the request.'),
      l('当前额外执行每日 50 封硬上限；相同 idempotencyKey 不会重复入队。', 'A hard cap of 50 messages per day is currently enforced; the same idempotencyKey is not queued twice.'),
    ],
  },
  {
    method: 'GET', path: '/api/linux-do-mail/inbox', group: 'linuxdoMail', auth: 'authenticated',
    title: l('读取 Linux DO Mail 最近来信', 'List recent Linux DO Mail messages'),
    description: l('通过 IMAP 读取 INBOX 最近 20 封邮件，或在服务器上搜索主题、联系人与正文。', 'Read the 20 most recent INBOX messages over IMAP, or search subjects, contacts, and body text on the server.'),
    request: 'Query · q?', response: '200 · { messages }',
    examplePath: '/api/linux-do-mail/inbox?q=release',
  },
  {
    method: 'GET', path: '/api/linux-do-mail/inbox/:uid', group: 'linuxdoMail', auth: 'authenticated',
    title: l('读取 Linux DO Mail 正文', 'Read a Linux DO Mail message'),
    description: l('通过数字 IMAP UID 只读获取受大小限制的邮件正文。', 'Read a size-limited message by numeric IMAP UID without changing mailbox state.'),
    request: 'Path · uid', response: '200 · { message }',
  },
  {
    method: 'GET', path: '/api/linux-do-mail/sent', group: 'linuxdoMail', auth: 'authenticated',
    title: l('读取 Linux DO Mail 发件记录', 'List sent Linux DO Mail messages'),
    description: l('读取或搜索当前账号最近 20 条 OmniMail 发件记录及排队、成功或失败状态。', 'List or search the 20 most recent OmniMail outbound records for the current account with queued, sent, or failed status.'),
    request: 'Query · q?', response: '200 · { messages }',
    examplePath: '/api/linux-do-mail/sent?q=invoice',
  },
  {
    method: 'GET', path: '/api/linux-do-mail/sent/:id', group: 'linuxdoMail', auth: 'authenticated',
    title: l('读取 Linux DO Mail 发件正文', 'Read a sent Linux DO Mail message'),
    description: l('从受当前用户约束的 D1 和 R2 记录读取发件正文与投递状态。', 'Read outbound content and delivery state from user-scoped D1 and R2 records.'),
    request: 'Path · id', response: '200 · { message }',
  },
]

export const adminOperationEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/admin/audit-logs', group: 'adminOperations', auth: 'admin',
    title: l('查询操作日志', 'Query audit logs'),
    description: l('按时间、类别和关键词查询脱敏审计记录并游标分页。', 'Query sanitized audit records by time, category, and keyword with cursor pagination.'),
    request: 'Query · days?, category=all|auth|account|user|mailbox|domain|invitation|message|icloud|gmail|microsoft|qq-mail|linuxdo-mail|system?, q?, limit?, cursor?', response: '200 · { logs, page }',
    examplePath: '/api/admin/audit-logs?days=7&category=qq-mail&limit=50',
  },
  {
    method: 'GET', path: '/api/admin/statistics', group: 'adminOperations', auth: 'admin',
    title: l('读取全站统计', 'Read site-wide statistics'),
    description: l('返回收件趋势、来源、发件人、平台用量和存储汇总。', 'Return receiving trends, sources, senders, platform usage, and storage summaries.'),
    request: 'Query · days=7|30|90?', response: '200 · { summary, daily, sourceDomains, topSenders, platform, storage }',
    examplePath: '/api/admin/statistics?days=30',
  },
  {
    method: 'GET', path: '/api/admin/deployment-check', group: 'adminOperations', auth: 'admin',
    title: l('执行部署自检', 'Run deployment checks'),
    description: l('检查 D1、R2、队列、Secret 和功能配置，不返回 Secret 明文。', 'Check D1, R2, queues, secrets, and feature configuration without returning secret values.'),
    request: 'No parameters', response: '200 · { groups, ready }',
  },
  {
    method: 'GET', path: '/api/admin/failed-messages', group: 'adminOperations', auth: 'admin',
    title: l('列出解析失败邮件', 'List failed messages'),
    description: l('返回仍可重试或需要清理的失败邮件摘要。', 'Return failed-message summaries that can be retried or cleaned up.'),
    request: 'No parameters', response: '200 · { total, messages }',
  },
  {
    method: 'POST', path: '/api/admin/failed-messages/:id/retry', group: 'adminOperations', auth: 'admin',
    title: l('重试失败邮件', 'Retry a failed message'),
    description: l('把指定失败邮件重新加入解析队列。', 'Requeue the selected failed message for parsing.'),
    request: 'Path · id', response: '200 · { ok: true }',
  },
  {
    method: 'GET', path: '/api/admin/mail-cleanup/preview', group: 'adminOperations', auth: 'admin',
    title: l('预估邮件清理', 'Preview mail cleanup'),
    description: l('按范围、类别和邮件年龄计算待清理数量、附件和空间。', 'Calculate messages, attachments, and bytes to clean by scope, category, and age.'),
    request: 'Query · scope=all|user|mailbox, scopeValue?, category, olderThanDays=1..3650', response: '200 · { filter, preview, batchLimit }',
    examplePath: '/api/admin/mail-cleanup/preview?scope=all&category=trash&olderThanDays=30',
  },
  {
    method: 'POST', path: '/api/admin/mail-cleanup', group: 'adminOperations', auth: 'admin',
    title: l('执行邮件清理', 'Run mail cleanup'),
    description: l('经数量复核后每批永久清理最多 50 封匹配邮件。', 'After count confirmation, permanently clean up to 50 matching messages per batch.'),
    request: 'JSON · scope, scopeValue?, category, olderThanDays, expectedCount, confirm=true', response: '200 · { deletedCount, deletedBytes, remainingCount }',
    exampleBody: { scope: 'all', scopeValue: '', category: 'trash', olderThanDays: 30, expectedCount: 12, confirm: true },
  },
  {
    method: 'GET', path: '/api/admin/messages', group: 'adminOperations', auth: 'superAdmin',
    title: l('查询全站邮件', 'Query site-wide messages'),
    description: l('主管理员按用户、邮箱、方向、文件夹、状态和时间筛选全站邮件。', 'Let the owner filter site-wide mail by user, mailbox, direction, folder, status, and age.'),
    request: 'Query · q?, user?, mailbox?, direction?, folder?, status?, days?, limit?, cursor?', response: '200 · { messages, page }',
    examplePath: '/api/admin/messages?folder=inbox&days=30&limit=30',
  },
  {
    method: 'PATCH', path: '/api/admin/messages/bulk', group: 'adminOperations', auth: 'superAdmin',
    title: l('批量管理全站邮件', 'Bulk-manage site-wide messages'),
    description: l('主管理员跨用户批量移入垃圾箱、恢复或永久删除邮件。', 'Let the owner move, restore, or permanently delete messages across users.'),
    request: 'JSON · ids[1..50], action=trash|restore|delete', response: '200 · { ok, updatedCount }',
    exampleBody: { ids: ['message_1', 'message_2'], action: 'trash' },
  },
  {
    method: 'GET', path: '/api/admin/messages/:messageId/attachments/:attachmentId', group: 'adminOperations', auth: 'superAdmin',
    title: l('读取任意用户附件', 'Read any user attachment'),
    description: l('主管理员下载或受限预览全站邮件附件，并写入审计日志。', 'Let the owner download or safely preview any attachment and write an audit event.'),
    request: 'Path · messageId, attachmentId; Query · preview=1?', response: '200 · attachment bytes',
    examplePath: '/api/admin/messages/:messageId/attachments/:attachmentId?preview=1', outputFile: 'attachment.bin',
  },
  {
    method: 'GET', path: '/api/admin/messages/:id/raw', group: 'adminOperations', auth: 'superAdmin',
    title: l('下载任意用户原始邮件', 'Download any raw message'),
    description: l('主管理员下载全站邮件的原始 EML，并记录访问审计。', 'Let the owner download any raw EML and record an access audit event.'),
    request: 'Path · id', response: '200 · message/rfc822', outputFile: 'message.eml',
  },
  {
    method: 'GET', path: '/api/admin/messages/:id', group: 'adminOperations', auth: 'superAdmin',
    title: l('读取任意用户邮件详情', 'Read any message details'),
    description: l('主管理员读取全站邮件正文、所属用户、线程和附件元数据。', 'Let the owner read any message body, owner, thread, and attachment metadata.'),
    request: 'Path · id', response: '200 · { message, thread }',
  },
]
