import { localized as l, type ApiEndpoint } from './apiCatalogTypes'

export const adminAccessEndpoints: ApiEndpoint[] = [
  {
    method: 'GET', path: '/api/admin/invites', group: 'adminAccess', auth: 'admin',
    title: l('查询邀请记录', 'Query invitations'),
    description: l('分页读取管理员创建的邀请、使用次数、状态和权限策略。', 'Page through invitations with usage, status, and policy details.'),
    request: 'Query · limit?, cursor?', response: '200 · { invites, page }',
    examplePath: '/api/admin/invites?limit=30',
  },
  {
    method: 'POST', path: '/api/admin/invites', group: 'adminAccess', auth: 'admin',
    title: l('创建账户邀请', 'Create an account invitation'),
    description: l('创建单次或多次、指定地址或自选地址的用户邀请。', 'Create single- or multi-use invitations with assigned or self-selected addresses.'),
    request: 'JSON · domain, accountRole, expiresInHours, accountLifetimeHours?, multiUse, addressMode, assignedLocalPart?, mailboxLimit, canCreateMailboxes, canReply, canTranslate',
    response: '201 · { invite, token }',
    exampleBody: { domain: 'example.com', accountRole: 'user', expiresInHours: 24, accountLifetimeHours: 0, multiUse: false, addressMode: 'self_selected', assignedLocalPart: '', mailboxLimit: 1, canCreateMailboxes: true, canReply: false, canTranslate: false },
  },
  {
    method: 'PATCH', path: '/api/admin/invites/:id/revoke', group: 'adminAccess', auth: 'admin',
    title: l('撤销邀请', 'Revoke an invitation'),
    description: l('立即使指定邀请失效，不影响已创建的账户。', 'Invalidate the invitation immediately without changing accounts already created from it.'),
    request: 'Path · id', response: '200 · { ok: true }',
  },
  {
    method: 'GET', path: '/api/admin/users', group: 'adminAccess', auth: 'admin',
    title: l('查询用户目录', 'Query the user directory'),
    description: l('分页读取用户、邮箱数量、配额与发信用量。', 'Page through users, mailbox counts, quotas, and sending usage.'),
    request: 'Query · limit?, cursor?', response: '200 · { users, totals, page }',
    examplePath: '/api/admin/users?limit=50',
  },
  {
    method: 'POST', path: '/api/admin/users', group: 'adminAccess', auth: 'admin',
    title: l('创建托管用户', 'Create a managed user'),
    description: l('由管理员直接创建账户并设置角色、配额和功能权限。', 'Let an administrator create an account with role, quota, and feature permissions.'),
    request: 'JSON · email, displayName, password, role?, status?, mailboxLimit?, storageQuotaMiB?, canCreateMailboxes?, canReply?, canTranslate?',
    response: '201 · { user }',
    exampleBody: { email: 'member@example.com', displayName: 'Member', password: 'strong-password', role: 'user', status: 'active', mailboxLimit: 1, storageQuotaMiB: 1024, canCreateMailboxes: true, canReply: false, canTranslate: false },
  },
  {
    method: 'PATCH', path: '/api/admin/users/:id', group: 'adminAccess', auth: 'admin',
    title: l('更新用户策略', 'Update a user policy'),
    description: l('修改非主管理员用户的角色、状态、邮箱上限、配额和能力。', 'Change role, status, mailbox limit, quota, and capabilities for a non-owner user.'),
    request: 'Path · id; JSON · role?, status?, mailboxLimit?, storageQuotaMiB?, canCreateMailboxes?, canReply?, canTranslate?',
    response: '200 · { user }',
    exampleBody: { status: 'active', mailboxLimit: 3, canReply: true },
  },
  {
    method: 'PATCH', path: '/api/admin/users/:id/outbound-rate-limit', group: 'adminAccess', auth: 'admin',
    title: l('覆盖用户发信限速', 'Override a user sending limit'),
    description: l('为指定用户设置每分钟和每日限额；null 表示继承全局值。', 'Set per-minute and daily limits for a user; null inherits the global value.'),
    request: 'Path · id; JSON · minuteLimit: number|null, dayLimit: number|null', response: '200 · { outboundRateLimit }',
    exampleBody: { minuteLimit: 5, dayLimit: 100 },
  },
  {
    method: 'POST', path: '/api/admin/users/:id/outbound-rate-limit/reset', group: 'adminAccess', auth: 'admin',
    title: l('清零用户发信计数', 'Reset a user sending counter'),
    description: l('清零指定用户当前分钟和 UTC 自然日的发信计数。', 'Reset the user’s current minute and UTC-day send counters.'),
    request: 'Path · id', response: '200 · { outboundRateLimit }',
  },
  {
    method: 'POST', path: '/api/admin/domains', group: 'adminAccess', auth: 'admin',
    title: l('添加收件域名', 'Add a receiving domain'),
    description: l('把已配置 Email Routing 的域名加入 OmniMail 管理。', 'Add a domain with configured Email Routing to OmniMail management.'),
    request: 'JSON · name', response: '201 · { domain }',
    exampleBody: { name: 'example.com' },
  },
  {
    method: 'PATCH', path: '/api/admin/domains/:name', group: 'adminAccess', auth: 'admin',
    title: l('启停收件域名', 'Enable or disable a receiving domain'),
    description: l('修改域名启用状态，关闭后停止该域名地址的收件和发信。', 'Change domain active state; disabling stops receiving and sending for its addresses.'),
    request: 'Path · name; JSON · isActive', response: '200 · { domain }',
    exampleBody: { isActive: false },
  },
  {
    method: 'DELETE', path: '/api/admin/domains/:name', group: 'adminAccess', auth: 'admin',
    title: l('删除空域名', 'Delete an empty domain'),
    description: l('删除没有邮箱地址的托管域名。', 'Delete a managed domain that has no mailbox addresses.'),
    request: 'Path · name', response: '200 · { ok: true }',
  },
]

export const adminSettingsEndpoints: ApiEndpoint[] = [
  {
    method: 'PATCH', path: '/api/admin/settings/registration', group: 'adminSettings', auth: 'admin',
    title: l('设置外部注册', 'Configure public registration'),
    description: l('开启或关闭外部注册，并选择密码或 Linux DO 注册方式。', 'Enable or disable public registration and select password or Linux DO registration.'),
    request: 'JSON · enabled, method=password|linuxdo', response: '200 · { registrationEnabled, registrationMethod }',
    exampleBody: { enabled: true, method: 'password' },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/registration-domains', group: 'adminSettings', auth: 'admin',
    title: l('设置注册邮箱后缀', 'Configure registration email domains'),
    description: l('配置最多 100 个允许或禁止注册的邮箱后缀。', 'Configure up to 100 allowed or blocked registration email domains.'),
    request: 'JSON · mode=blocklist|allowlist, domains[]', response: '200 · { registrationDomainPolicy }',
    exampleBody: { mode: 'blocklist', domains: ['mailinator.com'] },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/mail-refresh', group: 'adminSettings', auth: 'admin',
    title: l('设置自动刷新间隔', 'Configure automatic refresh'),
    description: l('设置所有 Web 用户的收件箱轮询间隔。', 'Set the Inbox polling interval for all web users.'),
    request: 'JSON · interval=0|5|10|30|60|120', response: '200 · { mailRefreshInterval }',
    exampleBody: { interval: 30 },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/mail-workspaces', group: 'adminSettings', auth: 'admin',
    title: l('设置邮箱功能入口', 'Configure mailbox workspace entries'),
    description: l('控制各可选邮箱工作区是否显示在 OmniMail 导航中。', 'Control whether each optional mailbox workspace appears in OmniMail navigation.'),
    request: 'JSON · iCloudWorkspaceEnabled, linuxDoMailWorkspaceEnabled, gmailWorkspaceEnabled, microsoftWorkspaceEnabled, qqMailWorkspaceEnabled, naverMailWorkspaceEnabled', response: '200 · all workspace switches',
    exampleBody: { iCloudWorkspaceEnabled: true, linuxDoMailWorkspaceEnabled: true, gmailWorkspaceEnabled: true, microsoftWorkspaceEnabled: true, qqMailWorkspaceEnabled: true, naverMailWorkspaceEnabled: false },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/remote-images', group: 'adminSettings', auth: 'admin',
    title: l('设置远程图片策略', 'Configure remote-image policy'),
    description: l('控制 HTML 邮件是否默认通过安全代理加载外部图片。', 'Control whether HTML mail loads external images through the safe proxy by default.'),
    request: 'JSON · enabled', response: '200 · { remoteImagesEnabled }',
    exampleBody: { enabled: false },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/unassigned-mail', group: 'adminSettings', auth: 'admin',
    title: l('设置无人收件', 'Configure unassigned mail'),
    description: l('控制未创建地址的来信是否进入主管理员收件箱。', 'Control whether mail for uncreated addresses enters the owner Inbox.'),
    request: 'JSON · enabled', response: '200 · { unassignedMailEnabled }',
    exampleBody: { enabled: true },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/official-extension', group: 'adminSettings', auth: 'superAdmin',
    title: l('启用官方浏览器扩展', 'Enable the official browser extension'),
    description: l('允许固定 Chrome Web Store 扩展 ID 使用授权流程。', 'Allow the fixed Chrome Web Store extension ID to use the authorization flow.'),
    request: 'JSON · enabled', response: '200 · { officialExtensionEnabled }',
    exampleBody: { enabled: true },
  },
  {
    method: 'PATCH', path: '/api/admin/settings/random-mailbox-prefix', group: 'adminSettings', auth: 'admin',
    title: l('设置随机邮箱前缀', 'Configure random mailbox prefix'),
    description: l('设置快速生成随机地址时使用的固定前缀。', 'Set the fixed prefix used when generating random mailbox addresses.'),
    request: 'JSON · prefix', response: '200 · { randomMailboxPrefix }',
    exampleBody: { prefix: 'omni-' },
  },
  {
    method: 'GET', path: '/api/admin/settings/outbound-rate-limit', group: 'adminSettings', auth: 'admin',
    title: l('读取全局发信限速', 'Read global sending limits'),
    description: l('读取全局开关、每分钟和每日默认发信限额。', 'Read the global switch and default per-minute and daily send limits.'),
    request: 'No parameters', response: '200 · { outboundRateLimit }',
  },
  {
    method: 'PATCH', path: '/api/admin/settings/outbound-rate-limit', group: 'adminSettings', auth: 'admin',
    title: l('更新全局发信限速', 'Update global sending limits'),
    description: l('设置是否启用限速以及全局每分钟、每日限额。', 'Set whether rate limiting is enabled and the global minute and daily limits.'),
    request: 'JSON · enabled, minuteLimit=1..100, dayLimit=1..10000', response: '200 · { outboundRateLimit }',
    exampleBody: { enabled: true, minuteLimit: 10, dayLimit: 200 },
  },
  {
    method: 'GET', path: '/api/admin/settings/storage', group: 'adminSettings', auth: 'admin',
    title: l('读取存储与保留策略', 'Read storage and retention policy'),
    description: l('读取备份、保留期、默认配额、草稿上限和最近备份状态。', 'Read backup, retention, default quota, draft limits, and latest backup state.'),
    request: 'No parameters', response: '200 · { storagePolicy }',
  },
  {
    method: 'PATCH', path: '/api/admin/settings/storage', group: 'adminSettings', auth: 'admin',
    title: l('更新存储与保留策略', 'Update storage and retention policy'),
    description: l('更新备份开关、各类保留期、默认配额和分角色草稿上限。', 'Update backup, retention periods, default quotas, and role-based draft limits.'),
    request: 'JSON · backupEnabled?, trashRetentionDays?, temporaryDataRetentionDays?, auditRetentionDays?, failedMessageRetentionDays?, defaultUserQuotaMiB?, defaultTemporaryQuotaMiB?, draftLimits?',
    response: '200 · { storagePolicy }',
    exampleBody: { backupEnabled: true, trashRetentionDays: 30, temporaryDataRetentionDays: 7, auditRetentionDays: 180, failedMessageRetentionDays: 7, defaultUserQuotaMiB: 1024, defaultTemporaryQuotaMiB: 256, draftLimits: { superAdmin: 5, admin: 5, user: 5, temporary: 3 } },
  },
  {
    method: 'POST', path: '/api/admin/backups', group: 'adminSettings', auth: 'admin',
    title: l('启动手动备份', 'Start a manual backup'),
    description: l('启动一次 D1 与邮件归档备份 Workflow。', 'Start a D1 and mail-archive backup Workflow run.'),
    request: 'No body', response: '202 · { id }',
  },
  {
    method: 'GET', path: '/api/admin/backups/objects', group: 'adminSettings', auth: 'superAdmin',
    title: l('浏览备份对象', 'Browse backup objects'),
    description: l('主管理员按前缀和游标浏览 BACKUP_BUCKET 对象。', 'Let the owner browse BACKUP_BUCKET objects by prefix and cursor.'),
    request: 'Query · prefix?, limit?, cursor?', response: '200 · { objects, page }',
    examplePath: '/api/admin/backups/objects?prefix=d1%2Fdaily%2F&limit=30',
  },
  {
    method: 'GET', path: '/api/admin/backups/download', group: 'adminSettings', auth: 'superAdmin',
    title: l('下载备份对象', 'Download a backup object'),
    description: l('主管理员下载经过安全路径校验的指定备份对象。', 'Let the owner download a validated backup object path.'),
    request: 'Query · key', response: '200 · backup bytes',
    examplePath: '/api/admin/backups/download?key=d1%2Fdaily%2Fbackup.sql', outputFile: 'backup.sql',
  },
  {
    method: 'POST', path: '/api/admin/backups/drill', group: 'adminSettings', auth: 'superAdmin',
    title: l('执行备份结构演练', 'Run a backup structure drill'),
    description: l('只读解析指定备份并校验结构，不导入或覆盖生产数据。', 'Parse and validate a backup read-only without importing or overwriting production data.'),
    request: 'JSON · key', response: '200 · { result }',
    exampleBody: { key: 'd1/daily/backup.sql' },
  },
  {
    method: 'GET', path: '/api/admin/version', group: 'adminSettings', auth: 'admin',
    title: l('检查系统版本', 'Check the system version'),
    description: l('读取当前版本与最新 GitHub Release，供管理员手动同步 Fork。', 'Read the current version and latest GitHub Release so administrators can sync their forks manually.'),
    request: 'No parameters', response: '200 · { currentVersion, latestVersion, updateAvailable, releaseUrl }',
  },
]
